### ISSUE TITLE
[V14] Connection issues and questions

### ISSUE THREAD

**Issue by pgi-jsanchez** [odoo-java/odoo-java-api#19]
Greetings.

I am currently testing the library connection with Odoo V14, but I got issues with this specific lines, 

https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L225

At line 225, tries to get the uid twice and the REST API web/session/authenticate uses the password instead of the api key to login, of course that's an issue for Odoo to implemented properly if required, but there's any reason to do this twice for a specific version?

https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L181

At line 181, I got an `TypeError: cannot marshal <class 'odoo.tools.misc.frozendict'> objects` exception trying to call res.users context_get, I commented this line and basically the project that I'm working on, works just fine for the moment. This context request is required?

Thanks

**Comment by flotho** [comment]
> Greetings.
Hi
> 
> I am currently testing the library connection with Odoo V14, but I got issues with this specific lines,
> 
> https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L225
> 
> At line 225, tries to get the uid twice and the REST API web/session/authenticate uses the password instead of the api key to login, of course that's an issue for Odoo to implemented properly if required, but there's any reason to do this twice for a specific version?
> 
I'll have a llok to this but I think that I connect twice because of the WIp on using jsonrpc instead of xmlrpc.

> https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L181
> 
> At line 181, I got an `TypeError: cannot marshal <class 'odoo.tools.misc.frozendict'> objects` exception trying to call res.users context_get, I commented this line and basically the project that I'm working on, works just fine for the moment. This context request is required?
> 
This one is already known and patched on odoo https://github.com/odoo/odoo/pull/75417
If you update your odoo instance you won't have the issue anymore.
