### ISSUE TITLE
Unable to start a Session

### ISSUE THREAD

**Issue by IgnaceHakizimana** [odoo-java/odoo-java-api#2]
Hello,
I'm trying to get data from Odoo server using this library but I'm getting an error.
The error is "Error while reading data from the server". 
Below is the code:
Session openERPSession = new Session("https://xyz-ltd4.odoo.com",8069, "xyz-ltd4", "my username",
				"my password");
Any support?

**Comment by flotho** [comment]
Hi @IgnaceHakizimana ,

Thanks for your question. 
The format is not the proper one.
You can find code there : https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L71
and some explanations here : https://sourceforge.net/p/openerpjavaapi/wiki/Examples/
Please be advise that the last thread is outdated but it presents you the proper parameter.

In the end this library is nos reaching through the http protocol so you only have to give the domain without port, then the port etc...

Hope it could help

**Comment by IgnaceHakizimana** [comment]
Hello @flotho ,

I've tried to follow your guidance but I still see another error: "Error while reading data from server:
Failed to read server's response: Connection timed out: connect"

Below is the source code:
Session openERPSession = new Session(RPCProtocol.RPC_HTTPS,"xyz-ltd4.odoo.com", 8069, "xyz-ltd4", "username","password");

Any further support?

**Comment by flotho** [comment]
Odoo enterprise ? which version ?
From now our module only deal with v12.
Maybe you could try on runbot intergration to check that you have proper syntax and then try to connect to your instance.

Regards

**Comment by IgnaceHakizimana** [comment]
I'm on Odoo version 13. Do we have another library supporting that version, let me know.
![image](https://user-images.githubusercontent.com/43338554/75548746-aa4b0b00-5a36-11ea-9808-944e4256b3f2.png)

**Comment by flotho** [comment]
From now, we didn't test on odoo v13, if you want to participate, change this part of code https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L152 accordingly and also update the readme in a proper PR I'll make a review.

Regards

**Comment by IgnaceHakizimana** [comment]
Hello @flotho , I changed the code and the session with the server started but now I'm getting an other error: "**Could not find model with name 'res.partner'**".  
Any support on that?

**Comment by flotho** [comment]
are you sure to be logged in on the correct DB
Do you have some logs from the client AND the server ?

**Comment by IgnaceHakizimana** [comment]
@flotho 
Yes, I'm logged in on the correct DB.

**Comment by flotho** [comment]
any logs from the server ? Are you hosted by Odoo SA or by your own ?

**Comment by IgnaceHakizimana** [comment]
I don't have server logs, I'm not a sudo user on the server. We are hosted on a local server.

**Comment by IgnaceHakizimana** [comment]
@flotho 
I don't have server logs, I'm not a sudo user on the server. We are hosted on a local server.

**Comment by flotho** [comment]
So it would be difficult to go further. Ask your sysadmin to get the Odoo server logs not the syslog but the odoo logs.
It's necessary to interpret how the query is received by Odoo and how v13 interpret the query.

Regards

**Comment by IgnaceHakizimana** [comment]
@flotho ,
Below are server logs, note that Dbname, IP address, and username represent their respective real names.
TypeError: search() takes from 2 to 6 positional arguments but 7 were given
2020-03-17 14:57:52,622 723558 INFO DbName werkzeug: IP address- - [17/Mar/2020 14:57:52] "POST /xmlrpc/2/object HTTP/1.1" 200 - 2 0.001 0.007
2020-03-17 14:58:05,038 719846 INFO ? werkzeug: IP address - - [17/Mar/2020 14:58:05] "GET / HTTP/1.0" 303 - 1 0.001 0.006
2020-03-17 14:58:05,051 731844 INFO ? werkzeug: IP address - - [17/Mar/2020 14:58:05] "GET /web HTTP/1.0" 303 - 2 0.002 0.007
2020-03-17 14:58:05,117 731616 INFO ? werkzeug: IP address - - [17/Mar/2020 14:58:05] "GET /web/database/selector HTTP/1.0" 200 - 6 0.004 0.059
2020-03-17 14:58:12,645 731844 INFO None werkzeug: IP address- - [17/Mar/2020 14:58:12] "POST /xmlrpc/2/db HTTP/1.1" 200 - 2 0.003 0.007
2020-03-17 14:58:12,695 717243 INFO DbName  odoo.addons.base.models.res_users: Login successful for db: DbName login:username from IP address 
2020-03-17 14:58:12,696 717243 INFO DbName odoo.service.common: successful login from ‘username ' using database DbName ' 
2020-03-17 14:58:12,696 717243 INFO DbName werkzeug: IP address- - [17/Mar/2020 14:58:12] "POST /xmlrpc/2/common HTTP/1.1" 200 - 20 0.007 0.034
2020-03-17 14:58:12,711 719846 INFO None werkzeug: IP address- - [17/Mar/2020 14:58:12] "POST /xmlrpc/2/db HTTP/1.1" 200 - 1 0.001 0.004
2020-03-17 14:58:12,737 723558 INFO DbName werkzeug: IP address- - [17/Mar/2020 14:58:12] "POST /xmlrpc/2/object HTTP/1.1" 200 - 7 0.003 0.011
2020-03-17 14:58:12,753 719846 ERROR DbName odoo.http: search() takes from 2 to 6 positional arguments but 7 were given 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 138, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3.7/site-packages/odoo/service/model.py", line 40, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3.7/site-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/service/model.py", line 175, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3.7/site-packages/odoo/service/model.py", line 164, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3.7/site-packages/odoo/api.py", line 407, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/api.py", line 380, in _call_kw_model
    result = method(recs, *args, **kwargs)
TypeError: search() takes from 2 to 6 positional arguments but 7 were given
2020-03-17 14:58:12,754 719846 INFO DbName werkzeug: IP Address - - [17/Mar/2020 14:58:12] "POST /xmlrpc/2/object HTTP/1.1" 200 - 2 0.001 0.006

**Comment by flotho** [comment]
Hi @IgnaceHakizimana , great,

Could you alos share the code you produce to make the search ?

**Comment by IgnaceHakizimana** [comment]
@flotho ,
Below is the code. I'm taking an example from https://sourceforge.net/p/openerpjavaapi/wiki/Examples/
@Controller
@EnableAutoConfiguration
public class UserController {

	@RequestMapping("/customers")
	@ResponseBody
	public ArrayList getCustomers() {
		ArrayList<String> customers = new ArrayList<String>();
		customers.add("John");
		
		Logger logger = Logger.getLogger(UserController.class.getName());

		Session openERPSession = new Session("Host Name", port, "Db Name", "Username", "Password");
		try {

			// startSession logs into the server and keeps the userid of the logged in user
			openERPSession.startSession();
			
			// ObjectAdapter partnerAd = openERPSession.getObjectAdapter("res.partner");
			ObjectAdapter partnerAd = openERPSession.getObjectAdapter("res.partner");
			
			//////
			////// Example code snippet goes here
			//////
		} catch (Exception e) {
			System.out.println("Error while reading data from server:\n\n" + e.getMessage());
			//logger.log(Level.WARNING, e.getMessage());
		}

		return customers;
	}

}

**Comment by flotho** [comment]
ok, @IgnaceHakizimana ,

could you provide a lookalike parameters so that I check you're running proper the session.
Thanks

**Comment by IgnaceHakizimana** [comment]
@flotho ,

@Controller
@EnableAutoConfiguration
public class UserController {

	@RequestMapping("/customers")
	@ResponseBody
	public ArrayList getCustomers() {
		ArrayList<String> customers = new ArrayList<String>();
		customers.add("John");
		
		Logger logger = Logger.getLogger(UserController.class.getName());

		Session openERPSession = new Session("crm.abc.com", 8069, "ABC_CRM_live", "crm@abc.com", "qzRtC{6rXN3N\RgL");
		try {

			// startSession logs into the server and keeps the userid of the logged in user
			openERPSession.startSession();
			
			// ObjectAdapter partnerAd = openERPSession.getObjectAdapter("res.partner");
			ObjectAdapter partnerAd = openERPSession.getObjectAdapter("res.partner");
			
			//////
			////// Example code snippet goes here
			//////
		} catch (Exception e) {
			System.out.println("Error while reading data from server:\n\n" + e.getMessage());
			//logger.log(Level.WARNING, e.getMessage());
		}

		return customers;
	}

}

**Comment by IgnaceHakizimana** [comment]
@flotho , Any update on what could be the source of this error?

**Comment by flotho** [comment]
Hi, @IgnaceHakizimana ,

Any chance to run the odoo server in debug mode and with dbfilter true.
I suspect that this API has not the option to set the version as in odoorpc in python. Your test would be appreciated for further debugging.

Regards

**Comment by IgnaceHakizimana** [comment]
@flotho 
It seems as if I can't go further debugging. Please, let me know if you test this library on this version of Odoo. 
Thank you for support.

**Comment by flotho** [comment]
What I can tell is that I succeed in reaching a v11 EE with the latest lib.
It's hosted behind a  reverse proxy with https . So without more logs from your side it will be difficult to reproduce.
Sorry

**Comment by flotho** [comment]
Hi @IgnaceHakizimana , I think we'll probably have a good option in #7 ,

coming soon

**Comment by flotho** [comment]
Hi @IgnaceHakizimana , could you please retry with the latest version? don't forget to add the lib jsonrpc4j in the lib folder.

Regards
