### ISSUE TITLE
[12.0] - Can't get model

### ISSUE THREAD

**Issue by jchancafe** [odoo-java/odoo-java-api#21]
Hello, first of all thanks for the effort to provide this library.
I am making a java application and when it tries to get the model, whatever it is, it shows the following error:

com.odoojava.api.OdooApiException: Could not find model with name 'res.partner'
	at com.odoojava.api.ObjectAdapter.validateModelExists(ObjectAdapter.java:123)
	at com.odoojava.api.ObjectAdapter.<init>(ObjectAdapter.java:88)
	at com.odoojava.api.ObjectAdapter.<init>(ObjectAdapter.java:79)
	at com.odoojava.api.Session.getObjectAdapter(Session.java:163)

I am using version 3.1.2:

  <dependency>
    <groupId>com.odoojava</groupId>
    <artifactId>odoo-java-api</artifactId>
    <version>3.1.2</version>
  </dependency>

thanks for your help.

**Comment by jchancafe** [comment]
Hello, 
I missed adding the start of the session, for that session.startSession() is used.
Example:
Row row = null;
try {
	Session session = sessionOdooService.getSession();
        //authenticating
	session.startSession(); 
	ObjectAdapter objectAdapter = session.getObjectAdapter(Constantes.MODEL_RES_PARTNER);
	FilterCollection filter = new FilterCollection();
	filter.add("id", "=",id);
	RowCollection rowCollection = objectAdapter.searchAndReadObject(filter, listaCampos);
	if(rowCollection != null && rowCollection.size() > 0) {
		return rowCollection.get(0);
	}
} catch (XmlRpcException | OdooApiException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}

**Comment by flotho** [comment]
Hi,
Thanks for the report.
Could you precise which version of Odoo you'r trying to query? at now, it doesn't work for v15 https://github.com/odoo-java/odoo-java-api/blob/master/src/main/java/com/odoojava/api/Session.java#L186
