### ISSUE TITLE
Search and read objects with offset and limit

### ISSUE THREAD

**Issue by agucortes** [odoo-java/odoo-java-api#3]
Hi,
i'm having this issue when i try to set the offset and the limits.
Seems the query isn't formating well
` File "/opt/odoo/odoo8/odoo-8.0/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "name"
LINE 2: ...                   WHERE "product_product".id IN ('name', 'l...`

I'm trying a simple code, just logging in and get products.
The search and read without the offset and limits is working Ok..
Any idea where to look?

EDIT:
the problem is reading the results. the search is returning nothing, thats why the ids is empty

**Comment by agucortes** [comment]
i think is the odoo version api.
I'm running version 8.
I working with the upto9 branch

**Comment by agucortes** [comment]
> Hi,
> i'm having this issue when i try to set the offset and the limits.
> Seems the query isn't formating well
> ` File "/opt/odoo/odoo8/odoo-8.0/openerp/sql_db.py", line 234, in execute res = self._obj.execute(query, params) DataError: invalid input syntax for integer: "name" LINE 2: ... WHERE "product_product".id IN ('name', 'l...`
> 
> I'm trying a simple code, just logging in and get products.
> The search and read without the offset and limits is working Ok..
> Any idea where to look?
> 
> EDIT:
> the problem is reading the results.

**Comment by agucortes** [comment]
ok, the problen is with the limit and offset
from the odoo docs it have to be a hashmap. And its passes as a array.

**Comment by agucortes** [comment]
i manually execute command... passing the hashmap... 
thats way, its seems to work, but not limiting the results

**Comment by flotho** [comment]
Hi, wich Odoo version do you run?
We correct the read method and possibly the seach method in the latest tags. could you please tell us if https://github.com/odoo-java/odoo-java-api/releases/tag/3.1.5 solve the issue?

Regards

**Comment by flotho** [comment]
Hi @agucortes , could you please test with the latest release
