### ISSUE TITLE
Missing ir.actions.report.xml

### ISSUE THREAD

**Issue by bwilmus** [odoo-java/odoo-java-api#4]
Hi,
 ir.actions.report.xml model in getReportList method  is missing.

We cannot print invoices from pentaho on Odoo 11 Enterprise instance.

Could you update please?

Regards,

Bernard

**Comment by bwilmus** [comment]
Maybe this can help you:
https://stackoverflow.com/questions/54441130/odoo-v12-api-get-invoice-pdf

**Comment by flotho** [comment]
solved by the PR #5
